### ISSUE TITLE
Config file data

### ISSUE THREAD

**Issue by rrees** [cobalt-org/cobalt.rs#171]
Is it possible to acces data in the config file, for example the name of the site, inside a template?

**Comment by nott** [comment]
There is no way to access config options from templates.

It makes sense to add `name`, `description` and `link` indeed.

**Comment by johannhof** [comment]
Data file support is pretty high on the list of things we should implement, though!

**Comment by bddenhartog** [comment]
It would be nice to support getting values from arbitrary keys defined in the configuration file, in order to support site-wide parameters. For example...

**.cobalt.yml**

```
name: my-cobalt-blog
source: "."
dest: "build"
ignore:
  - .git/*
  - build/*

[theme]
  themeStyle = "light"
```

...which could then be used in templates. _This is of course a contrived example; something like this specific example might be better controlled in the css development workflow._

**Comment by epage** [comment]
For @bddenhartog's issue, I'm working on that right now as #199 (see [Jekyll's documentation](https://jekyllrb.com/docs/configuration/#front-matter-defaults) for what it'll look like). 

While that could work for @rrees's issue, ideally we'd round out our supported [variables](https://jekyllrb.com/docs/variables/#site-variables).

Another idea, though I don't think either person's issues require this, is [data files](https://jekyllrb.com/docs/datafiles/)

**Comment by bddenhartog** [comment]
@epage I'm not seeing how my comment differs from the original request: we both want to access values defined in the configuration file.

I'd actually be _against_  implementing this in a similar manner to `jekyll`. It requires more bloat and is more confusing for little gain; `scope`, `scope.path`, and `scope.type` seem to be unnecessary. Why not just make all values in the configuration available, supporting arbitrary key names and chains?

**.cobalt.yml**

```
name: my-cobalt-blog
source: "."
dest: "build"
ignore:
  - .git/*
  - build/*

[someSection]
  a: "alphabet"
  b: "beehive"
  c: "cathartic"

foo: "bar"
baz: "qux"
```

IMHO, all but core "compiler keys" should be available in any template or page:

```
{{ someSection.a }}
{{ someSection.b }}
{{ someSection.c }}

{{ foo }}
{{ baz }}
```

"compiler keys" should _not_ be available, as they provide no value; `source`, `dest`, and `ignore` for example.

**Comment by epage** [comment]
I'm sorry, I misunderstood.  I assumed you were wanting to set page defaults rather than global values, for example being able to set a distinct theme for posts and for regular pages.  That is where the value of Jekyll's `defaults` (with its `scope`, `path`, and `type` ) shine.

Would the feature I suggested to rrees work for you, specifically the `site.[CONFIGURATION_DATA]` section on that page?  To me it sounds like what you are suggesting.

I also like what Hugo does with scoping the custom variables.  This makes it easier to add new features without breaking existing users and I'm planning on doing something like that for #198.  The challenge is this project aims for Jekyll compatibility.  I didn't set that goal and it'd be nice to get clarification on it from @johannhof but the value I see for it includes:
- Familiar
- Sharing themes
- Easier migration

In some ways, Jekyll compatibility gets in the way of performance and other goodies.    I wonder if we should have config or build flags for improved Jekyll compatibility for the places we find it gets in the way.

(might be good to document in CONTRIBUTING once we have a verdict on handling Jekyll compatibility)

**Comment by bddenhartog** [comment]
> I assumed you were wanting to set page defaults rather than global values, for example being able to set a distinct theme for posts and for regular pages.

I can definitely see where scoping would be helpful -- sounds like a cool feature!

> Would the feature I suggested to rrees work for you, specifically the site.[CONFIGURATION_DATA] section on that page? To me it sounds like what you are suggesting.

I must have totally glossed over that bit of the `jekyll` documentation. Having all parameters available through `site.keyName` would be great.

> this project aims for Jekyll compatibility

Playing devil's advocate -- if the goal is 1:1 feature parity with `jekyll`, why, as a user, should I not just use `jekyll`? I think offering unique features as seen fit by the `cobalt` organization and community is just as important in shaping the tool as using existing technology as a reference, if not more so.

**Comment by epage** [comment]
> Playing devil's advocate -- if the goal is 1:1 feature parity with jekyll, why, as a user, should I not just use jekyll? I think offering unique features as seen fit by the cobalt organization and community is just as important in shaping the tool as using existing technology as a reference, if not more so.

I do agree that we shouldn't settle for being 1:1 with Jekyll.  Jekyll compatibility should be a subset of what cobalt provides and possibly opt-in.

Granted, rust's package experience being so much better than Ruby's is why I'm using cobalt.  I just wanted to blog about my own rust project but I first needed to get cobalt up to snuff to do so.

**Comment by johannhof** [comment]
I think people misunderstood Jekyll compatibility, the initial motivation behind the project was to write Jekyll with less pain, but there's no reason we can't diverge. In an ideal world we could at some point write a migration script from Jekyll to Cobalt, that's why I'd love features to be "migrate-able". But really, diverging for sake of a better design is 100% fine by me.

**Comment by epage** [comment]
Thanks for the clarification.  I'll update my Issues appropriately.

**Comment by epage** [comment]
Does #292 solve this for you?

**Comment by rrees** [comment]
@epage actually the thing that I was trying to do originally (which was to do some SEO work) works just as well using data files. I've implemented the template changes I wanted to do originally via an `info` data file which means there might potentially mean there is some duplication or redundancy between the configuration file and the data files.

I'll keep playing around with the data files but I think this change does answer everything I would have wanted to do.

**Comment by epage** [comment]
Glad its working out!

I'll still keep this open because we need something to track `site.*` work and this at least sounds like it ;)
