### ISSUE TITLE
Host our own install script

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/cobalt.rs#179]
We're currently using the one from trust, but there might be several advantages to hosting our own.

**Comment by bddenhartog** [comment]
**If compiled binaries are provided with each release, I don't see a need for an install script.**

The user can be presented with the (preferred) option of installing via `cargo`, or the alternative option of downloading the binary themselves (through whatever method(s) they choose to employ).

I see a few issues with using the `install.sh` script from `japaric/trust`:

- It's an unmanaged, unaudited external dependency that this project currently suggests users execute on their machines
- There's no automated `PATH` setup based on the user's environment, and it installs to `~/.cargo/bin` by default. This is likely problematic for users who would prefer using the binary-download method of installation, as they probably don't have `cargo` installed (and thus likely do not have `~/.cargo/bin` in their `PATH`). As a user who doesn't want to install `cargo`, I probably have my own ideas about where I want to put executables that I want access to -- at the very least, I'd like to know that I'm responsible for adding the executable to my `PATH`.
- It's a shell script, and thus doesn't run on Windows machines

**Comment by ethagnawl** [comment]
> The user can be presented with the (preferred) option of installing via cargo

I just installed Cobalt for the first time and had this same thought. I was able to find the package on https://crates.io and install it using `cargo install cobalt-bin`, but a snippet or link would be very helpful. It would reduce friction and prevent users from accidentally installing the _other_ cobalt package.

**Comment by epage** [comment]
@ethagnawl so to clarify, this issue is about no relying on a third party for some of our install instructions but it sounds like instead you didn't find our install instructions?  If so, we should move this to a separate issue.  I'll go ahead and reply here, assuming that is the case, in hopes to reduce some back and forth.

We have install instructions at https://cobalt-org.github.io/docs/install/
- Would those have resolved your concerns
- If so, what got in the way of using them?
  - How did you hear about cobalt? Did it link out to anything?
  - What led you to crates.io?
  - Is there something we could do to make the "User documentation" link more attractive

**Comment by ethagnawl** [comment]
Sorry to hijack the issue, @epage. I only chimed in here because my concern and its solution were mentioned.

> Would those have resolved your concerns

No. I did find the install instructions, but wanted to use cargo instead of downloading and running a script hosted by a third party (at least, one that isn't the de facto third party). I also did not see any mention in the instructions of using cargo to install the application -- without building it from source.

I'll respond to your conditional questions because my answers may be useful to you all. 

> How did you hear about cobalt? Did it link out to anything?

A DuckDuckGo search for "rust static site generator".

> What led you to crates.io?

Habit.

> Is there something we could do to make the "User documentation" link more attractive

No. I don't think that's an issue.

Happy to continue the conversation in a new issue if you think it's worthwhile. I'm really enjoying the program so far. Thanks for your efforts!

**Comment by epage** [comment]
> If compiled binaries are provided with each release, I don't see a need for an install script.

> It's a shell script, and thus doesn't run on Windows machines

Install scripts are useful for CI, if nothing else.  crate-ci even offers CI templates based on it and it supports windows.

**Comment by epage** [comment]
I've created https://github.com/cobalt-org/cobalt-org.github.io/issues/71 for updating the website to the crate-ci version and am closing this out.
