### ISSUE TITLE
Create a new post or new page using a CLI command.

### ISSUE THREAD

**Issue by thowenzel** [cobalt-org/cobalt.rs#208]
It would be nice if the user can create a new post using a CLI command. Something like this:
`cobalt new post <title>`

This could create a new markdown-file withe the given name. 
I would like an handling similar to Hexo (https://hexo.io/docs/writing.html).

Are there any plans to implement something like this?

**Comment by bddenhartog** [comment]
I'd like a feature like this too, and would be happy to work on it myself. Right now, however, the `new` sub-command is used to generate a new cobalt project, not a component of a project (like a post, or page, or what-have-you).

Thought will have to be given to how to handle this; one idea I have is to "rename" the new-project-generation subcommand from `new` to one of `gen`, `generate`, or (my preferred) `init`. The `init` command follows the pattern of other tools, like `git`, `hg`, `npm`, etc. The other option, of course, is to use a name akin to `create` for the new subcommand for handling components of the cobalt project, e.g.:

    cobalt create post <title>
    cobalt create page <title>
    cobalt create page --template <template-name> <title>

This approach may be preferred, as it doesn't change existing workflows (people may have `cobalt new` tied in with certain automation tasks).

**Comment by thowenzel** [comment]
@bddenhartog Thanks, I like the approach your described. For me, the best solution iIn the sense of correct semantics) would be a rename of the new-project-generation subcommand to `init`. I think in this early stage of cobalt.rs is such a fundamental change still possible.

**Comment by epage** [comment]
Something that might be interesting for this is to open up cobalt to have subcommand plugins like cargo.  It might even be worth creating a new crate for subcommand plugins.  My main concern is how well it plays with clap.

See https://github.com/rust-lang/cargo/blob/master/src/bin/cargo.rs

**Comment by epage** [comment]
A related and useful command would be `cobalt publish`.  It could make the file no longer a draft and update the timestamp.

**Comment by epage** [comment]
#211 proposes we have a "skel" directory for users to place their skeleton files for creating new documents
- Should we initialize "skel" on "cobalt init" with default files or have a fallback to built-in versions if the name isn't overriden in "skel"?
  - Initializing it is more discoverable of what a user can customize
  - Users overriding our built-in skeletons is better for version migration. They just suddenly become available rather than having to `cobalt init` and copy the files over or creating a new migration command/option (though maybe we should do that anyways.

**Comment by epage** [comment]
If I do `cobalt new` from a "posts" folder, should it detect that and default to the "post" skeleton?

How do we handle detecting an optional skeleton parameter?

If the page name is meant to be a slug, that is easy because it has no spaces.  If the page is meant to be a reader-friendly-name, then it becomes more complicated.

One benefit of a slug is that we can have subdirectories included, like `cobalt new post category/title`.

**Comment by epage** [comment]
Minimal implementation created in #223.  This doesn't cover things like
- custom skeleton files
- custom paths
- using the CWD
- setting the `title` based on the file name used
- setting the date based on the creation (should this instead be a part of a `cobalt publish`?)

**Comment by Svenito** [comment]
> setting the date based on the creation (should this instead be a part of a cobalt publish?)

I would expect the date to be when it was created. Publish should update the `last_edited` field.

> setting the title based on the file name used

Also started this. Perhaps I can roll these things into the recent changes in the next few days

**Comment by epage** [comment]
>>    setting the date based on the creation (should this instead be a part of a cobalt publish?)
> I would expect the date to be when it was created. Publish should update the last_edited field.

That works for someone who publishes soon after creation.  I tend to be a bit slower in writing my blog posts :) but I can see either approach being reasonable.

**Comment by Svenito** [comment]
A good point. From all the static blogs I've used the date is always the creation date. And the last edited would be the timestamp of the file.

Also, how would you know the difference between a new publish and an update for a post?

**Comment by bddenhartog** [comment]
quote @Svenito
> Also, how would you know the difference between a new publish and an update for a post?

@epage and I have briefly talked about a deterministic property for all posts to differentiate this, such as a `draft<bool>` property, or a `drafts` directory where generated posts are initially placed.

**Comment by epage** [comment]
>  And the last edited would be the timestamp of the file.

See my comments for #197 for why mtime would not be too useful.

**Comment by epage** [comment]
#325 made major steps towards this issue.

`cobalt new "Page Title"` will create a `page-title.md` in the CWD
- title is accepted (needs quotes for multi-word)
- filename is assumed to be the title's slug unless otherwise specified
- destination is assumed to be cwd unless otherwise specified
- page vs post is inferred from the destination

`cobalt publish` has been introduced
- Removes `draft` flag
- Sets `date` to now

To simplify this process
- `cobalt init` only generates `.md` files.
- new posts (`init` or `new`) start as drafts

**Comment by bddenhartog** [comment]
Hey @epage, sorry for radio silence on my end - it's been a very, very busy past few months 👨‍💼 

Nice work with #325.

**Comment by epage** [comment]
Understandable and thanks!

The main thing I see as left is overriding the files dropped by `cobalt new`.

**Comment by epage** [comment]
Created a separate issue for overriding `cobalt new` since that might have its own set of discussion dealing with "how".

https://github.com/cobalt-org/cobalt.rs/issues/355
