### ISSUE TITLE
Propose not skipping hidden folders/files

### ISSUE THREAD

**Issue by Svenito** [cobalt-org/cobalt.rs#221]
The walkdir dir filter skips files prefixed with `_` and `.`. However hidden folders are required for example to prove keybase identity and setup Let's Encrypt verifications in a `.well-known` folder. 

Would it make sense to not skip hidden files and folders?

Although wrangling files like `.cobalt.yml`, `.gitlab-ci.yml`, etc would require them to be added to the ignore list in the config. This could be done by providing a default set of the most common config and directories.

Alternatively add an option to force include certain folders and files, somewhat like Pelican does

**Comment by Svenito** [comment]
Ref #211

**Comment by epage** [comment]
Let me see if I understand the use case.  There are source files (assets of templates) that are hidden or in hidden folders because in the output they are expected to be there and hidden?  You gave the example of `.well-known`.  `.htaccess` is an example from Jeyll's documentation.

As you pointed out, the challenge with this is there are a lot of dot files that someone would expect to not be copied over.  `.git` is another one. 

So we have two choices
- Copy dot files, requiring a user to blacklist files
- Don't copy dot files unless they are in a whitelist

I feel the latter would follow the principle of least surprise to users and is the direction I'm leaning.  Also, there is precedence in at least [Jekyll](https://jekyllrb.com/docs/configuration/#global-configuration).  I've actually started work on this in my dev branch but have been stalled on it because I've been spending time on polishing Liquid first.

**Comment by Svenito** [comment]
I agree with you that the 

> Don't copy dot files unless they are in a whitelist

is the preferred solution to this. But yes, you are right, there is a need to have certain hidden files and folders in your site structure for various reasons, `.well-known` being one example.

I am happy to carry on with this from your dev branch if you like. Currently I am looking at addressing #208 as it's something I also want

**Comment by epage** [comment]
My dev branch is a lot bigger change than just this.  If you'd like this sooner than later, feel free to add this feature and send a PR.

I was actually thinking of suggesting #208 to you.  I have a couple of ideas for it I'll post over there.

**Comment by Svenito** [comment]
No problem. I'll make a start soon. I've started in the new post issue, but not with subcommand plugins. I'll probably put that down the list and push this up then.
