### ISSUE TITLE
Support data files

### ISSUE THREAD

**Issue by epage** [cobalt-org/cobalt.rs#256]
Data files are ways to define custom attributes for use in pages in a centralized place.

## Use cases

- Defining menus (see #89 and #91)

## Data files in Hugo

- Lives in `./data`
- Supports `.yml`, `.yaml`, `.json` or `.toml`
- Accessed by `.Site.Data.path.relative.to.data.filename`

See https://gohugo.io/extras/datafiles/

## Data files in Jekyll

- Lives in `./_data`
- Supports `.yml`, `.yaml`, `.json` or `.csv` (with header row)
- Accessed by `site.data.path.relative.to.data.filename`

**Comment by gnunicorn** [comment]
So, my plan is to implement this after [SCSS](https://github.com/cobalt-org/cobalt.rs/pull/278), so I can finally move [AreWeWebYet](http://www.arewewebyet.org/) over to cobalt.

I would approach it this way:

 - Make `data_dir` configurable, but default to `_data`. 
 - support `yml`/`yaml`, `json` and `toml` by default (as all these are already in the dependencies, from what I can tell) 
 - it would do a preattempt build, creating the entire objects from the data directory and load that into memory and hand that to the template rending (rather than an on-access at rendering, which is better for big amounts of data but harder to implement and properly report errors on)
 - would make the data available at `site.data.*` as mentioned above.

Not sure yet about `csv` support, is that commonly used? Do we care about adding dependencies?

**Comment by epage** [comment]
Sounds great!

> it would do a preattempt build, creating the entire objects from the data directory and load that into memory and hand that to the template rending (rather than an on-access at rendering, which is better for big amounts of data but harder to implement and properly report errors on)

One annoyance is that we need to copy the data to every page's `Context`.  When I catch up with everything else, I'm hoping to modify Liquid to take in multiple `&Object` so we don't have to do these copies anymore.

> Not sure yet about csv support, is that commonly used? Do we care about adding dependencies?

I'm not sure how commonly csv is used.  The big benefit is for easy manipulation of the data in a spreadsheet program.

I'm not too worried about adding a dependency on the csv crate, I doubt its all that big.  I'm more concerned about external binaries.

**Comment by gnunicorn** [comment]
> One annoyance is that we need to copy the data to every page's Context. When I catch up with everything else, I'm hoping to modify Liquid to take in multiple &Object so we don't have to do these copies anymore.

Yeah, I saw that later. That isn't cool. Though, I am wondering: we are doing the rendering sequentially, so wouldn't it be enough to just reuse the same liquid-object and just modify it between renders?

**Comment by epage** [comment]
> Yeah, I saw that later. That isn't cool. Though, I am wondering: we are doing the rendering sequentially, so wouldn't it be enough to just reuse the same liquid-object and just modify it between renders?

Let's not worry about it unless someone gets into problems from the performance since I have plans for addressing it and hacking it up in the mean time might get messy.
