### ISSUE TITLE
How to check for missing data

### ISSUE THREAD

**Issue by badboy** [cobalt-org/cobalt.rs#363]
Previously I used the following snippet to add the site's title to the html if set or use another main title:

```
{{#title}}
<title>{{title}} - My cool website!</title>
{{/title}}
{{^title}}
<title>My cool website!</title>
{{/title}}
```

With the now strict enforcement on missing variables the build errors out.
Is there any way to get back the old behaviour?

**Comment by epage** [comment]
I understand doing
```
{% if title %}
{% endif%}
```
I am a bit confused by the syntax using `#/^`.  Does liquid support that?

> With the now strict enforcement on missing variables the build errors out.
Is there any way to get back the old behavior?

1. Every page now has a title, so no check is needed.  Granted, if you don't want the default title, ... there isn't a good way to handle that.
2. For any other existence tests, unfortunately there is not a way to do this yet, which is why I went through every site and added `nil` variables.

Thoughts on the possible solutions and workarounds?

#### Contains

Implement `contains` operator, see https://github.com/cobalt-org/liquid-rust/issues/155

```
{% if page contains "title" %}
{% endif%}
```

#### ~~`where` filter~~

Implement the `where` filter, see https://github.com/cobalt-org/cobalt.rs/issues/350
```
{{ [page] | where "title", nil }}
```

Oh drat, in trying to write this out I realized it doesn't work

#### Variable checks

This would restore the support for non-existent variables only in the following case:
```
{% if title %}
{% endif%}
```
but not in any other case (like `{{ title | upcase}}`)

I want to do this but I was initially holding off on this to catch migration bugs

#### Revert the restrictions

The following will not error
```
{% if title %}
{% endif%}
and
{{ title | upcase}}
```

I'm hoping a use case won't come up for this.

**Comment by badboy** [comment]
`{{#...}}` and `{{^...}}` are standard Mustache syntax, which I figured could work, so I tried and it did. :)
I think I'm fine with having the `contains` operator and might get around to implement it.

**Comment by epage** [comment]
cargo publish on cobalt v0.11.1 is happening right now.

I'm leaving this issue open to help track adding back in support for `{% if title %}`.
