### ISSUE TITLE
Loading `include`s relative to `source` is deprecated

### ISSUE THREAD

**Issue by wezm** [cobalt-org/cobalt.rs#366]
I encountered [this warning](https://github.com/cobalt-org/cobalt.rs/blob/7b3d25578ba1921f0815fe9fb1ea0255a5970a6c/src/template.rs#L63) when including a file from a Markdown file:

```
{{include 'rust2018/links.md'}}
```

I'm not sure what I'm supposed to do about it. Is there a non-relative form I'm supposed to use? Or some other way of using include?

**Comment by epage** [comment]
Sorry it doesn't make clear the action to take to move forward.

Originally, includes were relative to `<source>`.  Now they are relative to `<source>/_includes`. 

A couple reasons
- Performance: We can preload all of them
- Simplify a common use case: Most people were including things from `_layouts`.  This makes it so you don't have to reference into that path
- Separation of concern: People were storing snippets in `_layouts` rather than somewhere else, mucking up the folder with mixed content (and preventing optimizations).

If there is a sue case I missed by this change, please let me know so I can reconsider or adjust in other ways.

For reference, the originating issue is #328 and fix in #337

**Comment by wezm** [comment]
Thanks for the clarification. I think the missing detail for me was that they are now in `<source>/_includes`.
