### ISSUE TITLE
[convert-jekyll] define excerpt separator as option

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/cobalt.rs#375]
I know my use case is special, as it's WP -> Jekyll -> Cobalt but all the posts I convert uses `<!-- more -->` as separator. But I'd like to use the default separator for new posts.

So maybe allow option to define the separator in convert-jekyll subcommand?

**Comment by epage** [comment]
**The challenge** will be that this is a [non-default `excerpt_separator`](https://jekyllrb.com/docs/configuration/#default-configuration) so we can't build-in knowledge about it in a jekyll converter.

One option is we read the site config and apply the value in there to all files.  I'm a bit mixed about doing something like that.  On one hand, you generally don't change the excerpt separator globally after you've written posts, so it should be safe.  On the other hand, it adds a lot of noise to frontmatters besides yours.

**The other challenge** is that this issue doesn't sound like its about problems with conversion but the site author changing their mind.

So another option is for us to define some kind of subcommand or flag for people to migrate `excerpt_separator`s.  It'd take the current value and push it out to all frontmatters so that its safe to change it for new pages.  The problem with this is that having random subcommands or flags can clutter things up.

*grumble* Jekyll doesn't document the frontmatter variable [`excerpt_separator`](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/document.rb#L319)

**Comment by Geobert** [comment]
Converting the excerpt_separator is a great idea, but without Jekyll standard it's hard to do…

**Comment by epage** [comment]
>  but without Jekyll standard it's hard to do…

Can you clarify what you mean here?

**Comment by Geobert** [comment]
The missing doc you grumbled about ^^

**Comment by epage** [comment]
Its not documented but it seems we can count on it

**Comment by epage** [comment]
Closed for https://github.com/cobalt-org/cobalt-migrate-jekyll/issues/2
