### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/cobalt.rs#377]
What's the plan for supporting I8n?

for things like date (I had to hack the layout in order to translate date to French)

**Comment by epage** [comment]
We have #155 for dates.

What other localization requirements exist? Being english speaking gives me blind spots to this.,

**Comment by pickfire** [comment]
I think mainly on dates, even though I know other languages but I rarely use it on systems. Or docs maybe?

**Comment by epage** [comment]
For reference, here are some features Hugo has related to this: https://gohugo.io/content-management/multilingual/

> Or docs maybe?

Having translations of the docs would be a great way to test this kind of functionality out!

Not sure what the best practices are with that though in terms of edits being made to one language and how that is tracked for the other languages.  I'd need someone who is familiar or can research this stuff to look into it.

**Comment by pickfire** [comment]
@epage We can do translations. As an example, the english docs will normally be the main docs while the other languages can be used for example of how i18n was done in the main site.

**Comment by epage** [comment]
I've created https://github.com/cobalt-org/cobalt.rs/issues/392 for adding multi-language support for sites.

Since that is covered there, dates are covered in #155, and translating the site would be on https://github.com/cobalt-org/cobalt-org.github.io and is blocked until we have #392, I'm going to go ahead and close this out.
