### ISSUE TITLE
Check if page.data.x is defined

### ISSUE THREAD

**Issue by gibfahn** [cobalt-org/cobalt.rs#382]
Is there a way to check whether a variable is defined?

I've tried some suggestions from https://github.com/Shopify/liquid/issues/89 and https://github.com/Shopify/liquid/issues/223, and haven't found something that works.

Trying something like:

```md
{% if page.data.nav  %}
## Foo
{% endif %}
```

results in

```rust
Error: Failed to render content for "index.html"
Caused by: Rendering error: Invalid index `nav` for value 
`Object({"heading": Str("Gibson Fahnestock")})`
```

**Comment by epage** [comment]
Check my post on https://github.com/cobalt-org/cobalt.rs/issues/363

**Comment by epage** [comment]
Quick summary:

```
{% if page contains "title" %}
{% endif%}
```

and I plan to add back in `{% if page.data.nav  %}` support in the future.

**Comment by gibfahn** [comment]
I tried that but couldn't get it to work:

```rust
{% if page.data contains nav  %}
## Foo
{% endif %}
```

```
Error: Failed to render content for "index.html"
Caused by: Rendering error: Object key not found: "nav"
```

**Comment by epage** [comment]
So you've got it working now?

**Comment by gibfahn** [comment]
>So you've got it working now?

Yes, got it working.

Not sure how you do it for a top-level variable though (equivalent of `{% if nav %}`), is that currently possible?

**Comment by epage** [comment]
> Not sure how you do it for a top-level variable though (equivalent of {% if nav %}), is that currently possible?

At the moment, you can't.  I plan to add back in support for this.

The problem is previously, it treated any non-existent variable name as if it was `nil`.  When migrating across a major breaking change in cobalt, I wanted people people to know when they were accessing the old name of a variable, so I made them all errors.

As time passes and I'm more confident people have migrated, I'll be adding a special case to the `if` tag so that if its just a variable name, it will return `false` if it does't exist.
