### ISSUE TITLE
Feature Request: allow accessing file name as a variable

### ISSUE THREAD

**Issue by gibfahn** [cobalt-org/cobalt.rs#384]
I want to refer to the current filename in a template, in order to group images by page, I _think_ it should look like this:

```markdown
![some-image](../img/{{page.slug}}/some-image.png)
```

Referring to `{{page.permalink}}` like this works, but `{{page.slug}}` doesn't.

<br/>

BTW thanks for all the work on this, `cobalt` is getting really nice!

**Comment by epage** [comment]
You can see the list of supported variables at https://cobalt-org.github.io/docs/variables.html

I wasn't sure if there was a motivation for having the `slug`, so I didn't expose it.  I am a little hesitant to expose it for this use case because it seems very specialized.  I assume most sites can't get away with a single `slug` to uniquely identify a page which is what your use case needs.  Feel free to make the case.

Let's see if there is a reasonable workaround first.  Have you looked into filters on your permalink to extract what you need?

**Comment by gibfahn** [comment]
>I am a little hesitant to expose it for this use case because it seems very specialized. I assume most sites can't get away with a single slug to uniquely identify a page which is what your use case needs.

I guess it depends, but given `cobalt`'s focus on blog posts, I'd have thought having unique titles for posts would be quite common (I agree it's probably not something you could use for every page in your site).

I understand not wanting to meet every possible niche use-case, but I'd say on the other hand that if a variable is exposed in one place, it makes sense to expose it everywhere, otherwise the user has to remember/check where a variable is defined and where it isn't, which can seem a bit unintuitive/arbitrary.

>Let's see if there is a reasonable workaround first. Have you looked into filters on your permalink to extract what you need?

I had a look through the filters and didn't find anything generic that would work. I can do something like:

```liquid
{% assign filename = page.permalink | remove_first: 'posts/' | remove: '.html' %}
```

but there don't seem to be any wildcards in the remove/replace filters.

There's also a problem which is that I think I'd have to include that line in every single post, AIUI you can't assign to a variable in the `.liquid` template and use it in the pages that use it as a layout.
