### ISSUE TITLE
Rename command?

### ISSUE THREAD

**Issue by accidentalrebel** [cobalt-org/cobalt.rs#393]
I'm thinking of adding a functionality to [cobalt.el](https://github.com/cobalt-org/cobalt.el) that can rename a post's filename and frontmatter title field automatically with just one command. I was wondering if `cobalt.rs` has plans of adding a command similar to this? 

The reason for this is that sometimes I find myself changing my mind and wanting to change the file name along with the title field of a post.

**Comment by epage** [comment]
I want to keep cobalt approachable, including having focusing on a few key commands that are easily understood. 

Examples
- Added `new` to get people jump started on how to write a page, specific to the collection they are in
- Added `publish` mostly to help with formatting the date to our very specific format
- Combined `watch` and `serve` because I felt most people would want `watch` anyways and didn't care to explain the distinction.

So let's look at `rename`:
- Most useful for use between `new` and `publish`  because more care is needed after `publish` to handle a rename
- Auto-generates new file name from title

Anything more to add?  Any thoughts on the relative value of `rename`?

**Comment by epage** [comment]
btw if we ever add support for [`aliases`](https://gohugo.io/content-management/urls/#aliases) or related features, then this could automatically add aliases for non-draft pages.

**Comment by accidentalrebel** [comment]
> Auto-generates new file name from title

This is mainly the reason why I suggested this. Manually renaming the file and the title generally takes more steps.

I cannot think of any other value aside from the ones you mentioned though.

> btw if we ever add support for aliases or related features, then this could automatically add aliases for non-draft pages.
This is actually very helpful for published posts. The problem with manually renaming files is that the old generated URL becomes inaccessible.

**Comment by epage** [comment]
So my current thought on rename
- params
  - <source file>
  - target is handled similarly to `new`
- if the page is not a draft:
  - Take the old permalink (evaluated) and append it to a new `aliases`

Aliases would probably work like [Hugo](https://gohugo.io/content-management/urls/#aliases)
- Write out some predefined HTML that can be overwritten
- Unlike Hugo, I think I want aliases process last.  If a file already exists, a warning will be issued and nothing will be written.

The main question is how to handle the lookup for the redirection.  I think also making it a layout works.

**Comment by epage** [comment]
Alternatively, we could just drop redirection `.liquid` files rather than implement alias support.  This could be a short term thing and if enough of a use case comes up, we could add alias support.

This makes me think we might have a flag `--redirect` with options
- `auto`: based on draft or not, we choose the default
- `file`: drop a redirection file
- `none`: do nothing
- (future) `alias`: add an alias

**Comment by epage** [comment]
I've split out alias / redirect to #403
