### ISSUE TITLE
How to ignore swap files?

### ISSUE THREAD

**Issue by flosse** [cobalt-org/cobalt.rs#556]
Adding `**/*.swp` to `ignore` does not prevent me from this error:
```
 Failed to load layout ".posts.liquid.swp": stream did not contain valid UTF-8
```
Could you help?

**Comment by epage** [comment]
This seems odd.  dot files should already be ignored.  Do you have a repo to point me to so I can try to reproduce this?  It doesn't need to contain the dot file, I can add that myself.

**Comment by flosse** [comment]
@epage Thanks for the fast reply.
No, there is no repo at the moment :(

BTW: It's the current `v0.14.0`

**Comment by epage** [comment]
I tried to reproduce this but couldn't.  Could you morph https://github.com/epage/cobalt-issue-556 into something that fails?

I made sure my `.posts.liquid.swp` file can fail things by doing `cp .posts.liquid.swp && cobalt build` and I got a failure.

**Comment by epage** [comment]
Were you ever able to get my repo reproducing the problem or figure out what might be going on with your repo?

**Comment by lazysoundsystem** [comment]
A bit late on this, but it's related enough to re-open the issue.

In https://github.com/epage/cobalt-issue-556, opening `_layouts/default.liguid` in vim triggers:
```
Error: serve command failed
Info: caused by stream did not contain valid UTF-8
```
This fixes it, but I'm thinking there might be a reason it was set to `false`:
```
--- a/src/cobalt.rs
+++ b/src/cobalt.rs
@@ -324,7 +324,7 @@ fn parse_drafts(
 
 fn find_layouts(layouts: &path::Path) -> Result<files::Files> {
     let mut files = files::FilesBuilder::new(layouts)?;
-    files.ignore_hidden(false)?;
+    files.ignore_hidden(true)?;
     files.build()
 }
```

`$ gvim _includes/test.liquid` has the same effect, but I haven't found a quick way to fix that yet...

**Comment by skierpage** [comment]
As @lazysoundsystem reports, this is still a problem. If I use vim to edit a file in _layouts, it triggers `cobalt serve` to rebuild multiple times and each time it tries to load vim's swap file:
```
% Building from `/tmp/myBlog` into `/tmp/.tmpNFNwve`
WARN: Failed to load layout .default.liquid.swp
Building from `/tmp/myBlog` into `/tmp/.tmpNFNwve`
WARN: Failed to load layout .default.liquid.swp
Building from `/tmp/myBlog` into `/tmp/.tmpNFNwve`
WARN: Failed to load layout .default.liquid.swp
Building from `/tmp/myBlog` into `/tmp/.tmpNFNwve`
WARN: Failed to load layout .default.liquid.swp
Building from `/tmp/myBlog` into `/tmp/.tmpNFNwve`
WARN: Failed to load layout .default.liquid.swp
Building from `/tmp/myBlog` into `/tmp/.tmpNFNwve`
WARN: Failed to load layout .default.liquid.swp
Building from `/tmp/myBlog` into `/tmp/.tmpNFNwve`
WARN: Failed to load layout .default.liquid.swp
```
Cobalt should ignore the vim swap file because of its leading dot, but as @lazysoundsystem points out, `find_layouts` turns off `ignore_hidden`, so it doesn't ignore files beginning with `.` and `_`, and so it tries to process vim's binary swap file.

**Comment by epage** [comment]
For cases like this, its generally good to open a new issue than posting on one closed.  The original poster specifically mentioned posts.  Open ended issues of something not working in every case can never really be closed because you can't prove it, regressions can happen, etc.  Its better to focus each issue on more concrete reproduction cases.

As a side note, I can reproduce the layout problem and am looking at what should be done but further discussion should best be handled in a new issue.
