### ISSUE TITLE
Setup cobalt website

### ISSUE THREAD

**Issue by tak1n** [cobalt-org/cobalt.rs#73]
Currently the documentation written in the README is a little bit messy and incomplete.
I've started to create a github page at https://github.com/cobalt-org/website.

We probably can use cobalt to create this site :smile: 

The site should basically contain following:
- [ ] high level usage examples
- [ ] detailed examples for cli, config etc etc
- [ ] detailed rustdoc for public accessible traits etc (rustdoc?) if existent

The third point is kinda optional, because cobalt is a binary and not a lib.

But if some of the lib stuff we use for the executable is public accessible (`extern create cobalt`, `use cobalt::Whatever`) we should have good documentation for this public api.

**Comment by johannhof** [comment]
Not sure if I'd want to publish a rustdoc anytime soon. We keep the separation because it's good practice and would allow people to build upon it in *theory*, but it's currently in way too much Flux and we can't e.g. hold SemVer. Maybe we can publish one but we should definitely add a warning that we're not respecting SemVer for the internal API.

**Comment by tak1n** [comment]
Yep we should first concentrate on cobalt itself (executable program), but I just wanted to mention it because the executable uses public accessible stuff from the lib part.

And if we publish it to crates.io people should not assume because its public in the lib its part of a public api.

**Comment by epage** [comment]
Addressed by https://github.com/cobalt-org/cobalt-org.github.io/pull/17
