### ISSUE TITLE
"where" filter?

### ISSUE THREAD

**Issue by dillonfagan** [cobalt-org/cobalt.rs#780]
I'm working on a blog and need to match relations between blog posts and authors. The easiest way to do it seems to be liquid's _where_ filter, like this: `{% assign author = site.data.authors | where: "name", page.author | first %}`

Am I right that _where_ is not built-in? Is there any other clean way of accomplishing what I need to do?

**Comment by epage** [comment]
Thanks for bringing this to our attention!  It was originally a Jekyll-extension (which we eventually want to implement, see https://github.com/cobalt-org/liquid-rust/issues/311) but it is now part of liquid-proper and is being tracked in https://github.com/cobalt-org/liquid-rust/issues/418.

I'm going to put an estimate of 1 week before I'll have put together enough time to implement and release support for this.  If that doesn't work, I'd welcome the contribution of where support.

The first workaround that comes to my mind is to use `{% capture %}` but that gets messy because the `author` you want to capture is structured data (also wanting to add conversion to/from json which would allow workarounds).

Closing in favor of the liquid issue (wasn't paying attention or I would have just moved this one)

**Comment by epage** [comment]
I am release v0.16 right now.

The breaking change is related to include tags and documented in CHANGELOG.md
