### ISSUE TITLE
Cobalt serve updates your RSS and JSON feeds to link to your localhost

### ISSUE THREAD

**Issue by natjms** [cobalt-org/cobalt.rs#834]
I'm not sure if this is intentional or not so feel free to close it if that's the case; this was just something that I noticed today while rebuilding my site:

When you run `cobalt serve`, the domain of all the links in your website's RSS and JSON feeds is changed from whatever you have it set to in your configuration file to localhost:3000. If you run `cobalt build` afterwards, it changes them all back, but otherwise they'll stay like that even after you've closed the server.

![Diff of my site's RSS feed file before and after running cobalt serve](https://user-images.githubusercontent.com/15806798/108732075-992ac200-7503-11eb-86cc-4a8610326a5a.png)

[Apparently I've been making this mistake for a while](https://github.com/natjms/njms.ca/blob/fd704f262d9d9494e5baca6c23f2da16953287cf/feed.json) and it hasn't really bothered me because the odds of someone actually following my RSS feed are pretty low, but I can imagine this being a bit problematic for anyone running a larger blog. If this is intentional (and I can see it being useful in debugging), it might be a good idea either to document it or possibly have a hook for when the server shuts down to change it back

I just updated Cobalt and it definitely still happens on v0.16.4. I've only tested it on my Mac running High Sierra 10.13.6

**Comment by epage** [comment]
We intentionally change the base url during `serve` so all links can work (for when people do absolute links in their pages) which also allows local testing for sitemap and RSS.

Some of us generate our site from CI, rather than locally, which is why this hasn't been raised before.

I suspect what we should do is have `serve` also overwrite the destination to a tempdir (and print it out).
