### ISSUE TITLE
RFC: Add Ed Page to `authors` field

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/cobalt.rs#839]
Why?

I think he deserves it as he is the only one working (more or less) actively on the project and the creators are not really involved anymore.

**Comment by FantasyCookie17** [comment]
I don't know about much of the development happening here (seems somewhat frozen recently anyway, with only small stuff happening, not that that's problematic given it works quite well already, for me at least, then again, perhaps I myself should start looking through issues and see where I could help), however, from what I've seen so far, him being pretty much the only person who ever interacted with me here so far, and the only one I've been seeing doing commits, I definitely would support this.

**Comment by epage** [comment]
Development slowed because of both real life and I was spread too thin. For the last while, I was focused on wrapping up the distractions and I'm nearly complete. I am turning my attention back to Cobalt. My initial focus is on a re-architecture which should both make it easier to add new features (its a pain right now) and even faster, including cobalt serve doing partial rebuilds.
