### ISSUE TITLE
serve should build sass files

### ISSUE THREAD

**Issue by elpiel** [cobalt-org/cobalt.rs#949]
My sass files are in `_sass` but they too don't seem to get **built** nor **served**  when I open `localhost:3000`

in the configuration I have:
```
assets:
  sass:
    style: nested
```
PS: `style` value is renamed with Serde and I don't know why the documentation says it's `CamelCase`

**Comment by 0xc0000007b** [comment]
Hi @elpiel. What URL did you use to try and access the image in your images directory? And what's the relative path of the file exactly? Finally, do you see the image in your `_site` directory after a build?

**Comment by elpiel** [comment]
Regarding source files - they do get copied, I've made a typo in one of the file names, that's why it wasn't showing.

I'm still having a problem with the sass files though.

**Comment by 0xc0000007b** [comment]
Did you look at the example sites in the docs? Some are using Sass and may help you model and solve your own problem.

**Comment by elpiel** [comment]
Where are these example sites?

**Comment by 0xc0000007b** [comment]
Example sites here: https://cobalt-org.github.io/help/

**Comment by elpiel** [comment]
> Example sites here: https://cobalt-org.github.io/help/

Most of them either don't use Cobalt anymore or don't have `_sass` folders

**Comment by epage** [comment]
> [2021-12-05T10:42:10Z TRACE cobalt_core::source] "/home/elpiel/PROJECTS/Personal/crates-categories/_sass": ignored "/_sass"


Is that where you are locating your sass files?

From the docs:

> Sass snippets that can be imported into your .scss files.

You should be able to put your sass files anywhere and they will get replaced by css files in the destination.

**Comment by elpiel** [comment]
Yeahz that was the place.
I think we can change the wording in the docs. I though that's where the sass files can live not the snippets only.

**Comment by 0xc0000007b** [comment]
Assume the following Sass files include the `_partials` in the same directory with the the files which `@import` them: https://github.com/oxalorg/sakura/tree/cef07fafd920e5bc22a69ad86714cb8462b0a4e2/scss

Using Cobalt you may keep the `_main.scss` file in the `_sass` directory (since it's a "snippet" a.k.a. partial) and `@import` it into a `another.scss` file kept elsewhere in the project.

**Comment by 0xc0000007b** [comment]
To demystify a little. Assume the following Sass files:
https://github.com/oxalorg/sakura/tree/cef07fafd920e5bc22a69ad86714cb8462b0a4e2/scss

Using Cobalt you may keep the `_main.scss` file in the `_sass` directory (since it's a "snippet" a.k.a. partial) and `@import` it into a `sakura.scss` file kept elsewhere in the project. The result will be a compiled CSS file in the destination directory.

**Comment by elpiel** [comment]
Thanks for clarifying it.
I will look into updating the docs.
